# Generated by Django 4.2.23 on 2025-08-29 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WS_chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='content',
            new_name='user_message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='role',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='bot_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
